

services:
  # PostgreSQL database
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fablee54
    networks:
      - backend_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # RabbitMQ message broker
  rabbitmq:
    image: rabbitmq:3-management  # Includes the management UI
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"    # RabbitMQ broker port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq





  # Eureka Server
  eureka-server:
    build:
      context: ./eureka-server  # Path to the eureka-server module
      dockerfile: Dockerfile
    container_name: eureka_server
    ports:
      - "8761:8761"  # Default Eureka Server port
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_INSTANCE_HOSTNAME: eureka-server
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
    networks:
      - backend_network


networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
