

server:
  port: 8095


spring:
  config:
    import: "classpath:/application-common.yaml"

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: fablee54
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
