spring:
  application:
    name: api-gateway
  http:
    multipart:
      enabled: true
  cloud:
    gateway:
      routes:
        - id: file-manager
          uri: lb://file-manager
          predicates:
            - Path=/api/**
  server:
    port: 8080
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
