spring:
  redis:
    host: localhost
    port: 6376
  config:
    import:
#      - "classpath:/eureka-url.yaml"
      - "classpath:/security-properties.yaml"
  application:
    name: api-gateway
  http:
    multipart:
      enabled: true
  cloud:
    gateway:
      routes:
        - id: file-manager
          uri: lb://file-manager
          predicates:
            - Path=/api/**
          filters:
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 10
              redis-rate-limiter.burstCapacity: 20
              redis-rate-limiter.requestedTokens: 1
              key-resolver: "#{@ipKeyResolver}"
  server:
    port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

