spring:
  redis:
    host: localhost
    port: 6379
  config:
    import:
      - "classpath:/security-properties.yaml"
  application:
    name: api-gateway
  http:
    multipart:
      enabled: true
  cloud:
    gateway:
      routes:
        - id: request-manager
          uri: lb://request-manager
          predicates:
            - Path=/api/**
          filters:
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 10
              redis-rate-limiter.burstCapacity: 20
              redis-rate-limiter.requestedTokens: 1
              key-resolver: "#{@ipKeyResolver}"

        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 3
                redis-rate-limiter.requestedTokens: 3
                key-resolver: "#{@ipKeyResolver}"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8443

