jwt:
  secret: 3ee973bd66a793eca0b7261bd924836ff24db61f0acfb

aws:
  access-key: AKIARZDBIECRMNWQE5PB
  secret-key: 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
  upload-bucket-name: amzn-s3-converter-bucket
  region: eu-north-1