server:
  port: 8085

spring:
  application:
    name: converter
  config:
    import:
       - "classpath:/application-common.yaml"
       - "classpath:/rabbitmq-config.yaml"
       - "classpath:/aws-properties.yaml"
