#jwt:
#  secret: 3ee973bd66a793eca0b7261bd924836ff24db61f0acfb

#aws:
#  access-key: AKIARZDBIECRMNWQE5PB
#  secret-key: 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
#  upload-bucket-name: amzn-s3-converter-bucket
#  region: eu-north-1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: fablee54
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: "guest"
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
